version: '2'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
        - ./:/var/www
        - ./docker/nginx/ssl:/etc/nginx/ssl
        ports:
        - "80:443"
        links:
        - php-fpm
    admin:
        build:
            context: ./
            dockerfile: docker/admin.docker
        volumes:
            - ./:/var/www
            - ./docker/adminnginx/ssl:/etc/nginx/ssl
        ports:
            - "8083:443"
        links:
            - php-fpm
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
        - ./:/var/www
        links:
        - db
        environment:
        - "DB_PORT=3306"
        - "DB_HOST=db"
    php-cli:
        build:
            context: ./
            dockerfile: docker/php-cli.docker
        volumes:
        - ./:/var/www
        links:
        - db
        environment:
        - "DB_PORT=3306"
        - "DB_HOST=db"
        tty: true
    db:
        image: mysql:5.7
        volumes:
        - ./storage/docker/mysql:/var/lib/mysql
        environment:
        - "MYSQL_ROOT_PASSWORD=secret"
        - "MYSQL_USER=app"
        - "MYSQL_PASSWORD=secret"
        - "MYSQL_DATABASE=app"
        ports:
        - "33061:3306"
    node:
        image: node:8.12.0-jessie
        volumes:
        - ./:/var/www
        working_dir: /var/www
        tty: true

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
        - db
        depends_on:
        - db
        ports:
        - 9191:80
